name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
          activate-environment: ci

      - name: Upgrade pip
        shell: bash -l {0}
        run: python -m pip install --upgrade pip

      - name: Install package (with dev + all extras)
        shell: bash -l {0}
        run: |
          pip install -e .[dev,all]

      - name: Lint with Ruff
        shell: bash -l {0}
        run: |
          ruff check .

      - name: Format check with Black
        shell: bash -l {0}
        run: |
          black --check .

      - name: Install cdiutils
        shell: bash -l {0}
        run: |
          pip install git+https://github.com/clatlan/cdiutils@dev

      - name: Install pyvkfft (conda-forge)
        shell: bash -l {0}
        run: |
          conda install -y -c conda-forge pyvkfft

      - name: Install pynx
        shell: bash -l {0}
        run: |
          pip install git+https://gitlab.esrf.fr/favre/PyNX@devel

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest